#!/bin/bash

source ./0compose/utils.sh
source ./0compose/constant.sh

c=$1
shift;

case "$c" in
  run)
    ./0compose/run.sh "${@}"
    ;;

  logs)
    ./0compose/logs.sh "${@}"
    ;;

  exec)
    ./0compose/exec.sh "${@}"
    ;;

  stop)
    ./0compose/stop.sh "${@}"
    ;;

  *)
    echo $"Usage: $0 {run|logs|exec|stop}"
    exit 1

esac
